# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.2.7/s3-bucket.yaml"
stack_name: "amp-mayo-sinai"
stack_tags:
  OwnerEmail: 'william.poehlman@sagebase.org'
  CostCenter: "Model AD-IU / 116000"
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "NDR"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "amp-ad-wgs"
  # The resource owner
  OwnerEmail: 'william.poehlman@sagebase.org'

  # The following parameters are only examples they are not required.
  # You may omit them if you do not need to override the defaults.

  # (Optional) true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: 'true'
  # (Optional) Synapse username (default: ""), required if AllowWriteBucket=true
  SynapseUserName: 'wpoehlm'
  # (Optional) Allow accounts, groups, and users to access bucket (default is no access).
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'   # Required ARN for a synapse bucket
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/william.poehlman@sagebase.org'

  # Restrict downloading files from this bucket to only AWS resources (e.g. EC2 , Lambda)
  # within the same region as this bucket.  This will not allow even the owner of the bucket
  # to download objects in this bucket when not using an AWS resource in the same region!
  SameRegionResourceAccessToBucket: "true"

  # Enable transition to deep archive storage
  EnableDataLifeCycle: 'Enabled'
  LifecycleDataStorageClass: 'DEEP_ARCHIVE'
