# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template_path: "remote/s3-bucket.yaml"
stack_name: "AMP-Emory-Bucket"
parameters:
  # The Sage deparment for this resource
  Department: "SysBio"
  # The Sage project this resource will be used for
  Project: "AMP-Emory"
  # true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: "true"
  # Synapse username
  SynapseUserName: "yooree"
  # true to encrypt bucket, false (default) for no encryption
  EncryptBucket: "true"
  # Bucket owner's email address
  OwnerEmail: 'ampadportal@sagebase.org'
  # Allow accounts, groups, and users to access bucket.
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'
    - 'arn:aws:iam::743849566882:user/dduong'
    - 'arn:aws:sts::563295687221:assumed-role/sandbox-developer/phil.snyder@sagebase.org'

hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/s3-bucket.yaml --create-dirs -o templates/remote/s3-bucket.yaml"
  after_create:
    - !synapse_bucket_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"
