# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template_path: templates/SynapseExternalBucket.yaml
stack_name: AMP-WGS-MSSM-Transfer
parameters:
  # true for read-write bucket, false (default) for read-only bucket 
  AllowWriteBucket: "true"
  # Synapse username
  SynapseUserName: "brucehoff"
  # true to encrypt bucket, false (default) for no encryption
  EncryptBucket: "true"
  # Bucket owner's email address
  OwnerEmail: bruce.hoff@sagebase.org
hooks:
  after_create:
    - !synapse_external_bucket
