project_code: sage-bionetworks
profile: {{ var.profile | default("default") }}
region: {{ var.region | default("us-east-1") }}
template_bucket_name: bootstrap-awss3cloudformationbucket-114n2ojlbvj21
template_key_prefix: {{ environment_variable.TRAVIS_BRANCH | default("testing") }}