template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.3.38/EC2/jc-ec2-linux.j2"
stack_name: "EC2-gene-co-expression"
stack_tags:
  Department: "TBD"
  Project: "TBD"
  OwnerEmail: "jake.gockley@sagebase.org"
  CostCenter: "TBD"
sceptre_user_data:
  Distro: "aws"
parameters:
  JcUserId: "jake.gockley@sagebase.org"
  InstanceType: "c6i.32xlarge"
  VolumeSize: "100"        # in GB
  VpcSubnet: "PrivateSubnet"    # For public access change to PublicSubnet

  # do not change these
  VpcName: "computevpc"
  KeyName: "scicomp"
  JcConnectKey: !ssm "/infra/JcConnectKey"
  JcServiceApiKey: !ssm "/infra/JcServiceApiKey"
  JcSystemsGroupId: !ssm "/infra/JcSystemsGroupId"
