# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.2.7/s3-bucket.yaml"
stack_name: "gates-ki-001"
stack_tags:
  OwnerEmail: 'thomas.yu@sagebase.org'
  CostCenter: "BMGF-Ki / 30144"
parameters:
  # The Sage deparment for this resource
  Department: "SysBio"
  # The Sage project this resource will be used for
  Project: "GatesKi"
  # true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: "true"
  # Synapse username
  SynapseUserName: "gates-ki-service"
  # true to encrypt bucket, false (default) for no encryption
  EncryptBucket: "true"
  # Bucket owner's email address
  OwnerEmail: 'thomas.yu@sagebase.org'
  # Allow accounts, groups, and users to access bucket.
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'
  # Enable Intelligent-tiering storage
  EnableDataLifeCycle: 'Enabled'
  LifecycleDataStorageClass: 'INTELLIGENT_TIERING'
