# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template:
  type: "http"
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.8.3/templates/S3/synapse-external-bucket.j2"
stack_name: "htan2-testing1"
stack_tags:
  OwnerEmail: 'aditi.gopalan@sagebase.org'
  CostCenter: "HTAN-DFCI / 120100"
parameters:
  # The following parameters are only examples they are not required.
  # You may omit them if you do not need to override the defaults.
  # (Optional) true (default) to encrypt bucket, false for no encryption
  # (Optional) true for read-write bucket, false (default) for read-only bucket
  #BucketName: "htan2_testing1"  # must match bucket name in data/s3-synapse-sync-bucket-vars.yaml
  AllowWriteBucket: 'true'
  SameRegionResourceAccessToBucket: 'true'
  # (Optional) Synapse username (default: ""), required if AllowWriteBucket=true
  # (Optional) Allow accounts, groups, and users to access bucket (default is no access).
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'   # Required ARN for a synapse bucket
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/aditi.gopalan@sagebase.org'
  EnableDataLifeCycle: 'Enabled'
  LifecycleDataStorageClass: 'INTELLIGENT_TIERING'
