# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template:
  type: "http"
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.8.3/templates/S3/synapse-external-bucket.j2"
stack_name: "htan2-crc-syn63298073"
stack_tags:
  OwnerEmail: 'aditi.gopalan@sagebase.org'
  CostCenter: "DFCI HTAN / 120100"
parameters:
  BucketName: "htan2-crc-syn63298073"
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'   # Required ARN for a synapse bucket
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/aditi.gopalan@sagebase.org'
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/adam.taylor@sagebase.org'
  EnableDataLifeCycle: 'Enabled'
  LifecycleDataStorageClass: 'INTELLIGENT_TIERING'
sceptre_user_data:
  SynapseIDs:
    - 3474475  # aditigopalan
