# Provision an EC2 instance
template_path: "remote/managed-ec2-v10.j2"
stack_name: "miac-data-model-web-ec2"
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "CompOnc"
  # The Sage project this resource will be used for
  Project: "CSBC"
  OwnerEmail: "milen.nikolov@sagebase.org"

  # Default account settings, leave alone unless you plan to override
  VpcName: "computevpc"
  KeyName: "scicomp"
  AMIId: "ami-0b898040803850657"      # Amazon Linux 2 AMI 2.0.20190618 x86_64 HVM gp2

  # Settings have default values but can be overriden. Set the below
  # parameters *only* if you want to override the defaults.

  # (Optional) EC2 instance type, default is "t2.nano" (other available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t2.medium"
  # (Optional) EC2 boot volume size in GB, default is 8GB, Max is 1000GB
  VolumeSize: "24"
  # (Optional) Base instance on AMI (default: ami-082278746f893d99c) (supported distros: AWS linux)
  # AMIId: "ami-0de53d8956e8dcf80"
  # (Optional) Run EC2 in a subnet (default: PrivateSubnet) (valid values: PrivateSubnet or PublicSubnet)
  VpcSubnet: "PublicSubnet"
  # (Optional) Set true to enable daily backups (default: false)
  # BackupEc2: "true"
  # (Optional) Number of daily backups to keep (default: 7) (valid range: 1-180)
  # SnapshotCount: "3"

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm "/infra/JcConnectKey"
  JcServiceApiKey: !ssm "/infra/JcServiceApiKey"
  JcSystemsGroupId: !ssm "/infra/JcSystemsGroupId"


sceptre_user_data:
  # (Optional) Expose ports to incoming traffic (default is no open ports) (valid range: 1-65535)
  OpenPorts: ["8000", "9200"]

# For CI system (do not change)
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.2.7/managed-ec2-v10.j2 --create-dirs -o templates/remote/managed-ec2-v10.j2"
  after_create:
    - !ec2_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"
