# Provision a public load balancer in front of private miniDREAM EC2
# Based on the PR here: https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/504/files

template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.4.0/managed-alb-https-v2.yaml"
stack_name: "minidream-rstudio-2022-ec2-alb"
dependencies:
  - "prod/minidream-rstudio-2022-ec2.yaml"
parameters:
  Department: "SCCE"
  Project: "CSBC"
  OwnerEmail: "lingling.peng@sagebase.org"
  Ec2InstanceId: !stack_output_external "minidream-rstudio-2022-ec2::Ec2InstanceId"
  SSLCertificateIdArn: "arn:aws:acm:us-east-1:055273631518:certificate/992c2d49-579a-465e-beff-1a08c284f7db"
  VpcId: "vpc-e66bd19d"   # computevpc
  AppPort: "443"          # nginx reverse proxy
  Subnets: "subnet-21a68d7c,subnet-4f3e2b2b,subnet-77d1e458"  # public subnets
stack_tags:
  CostCenter: "CSBC - NCI / 101300"
# After deployment, Ec2SecurityGroup must be manually attached to the EC2 referenced by Ec2InstanceId:
# https://github.com/Sage-Bionetworks/aws-infra/blob/v0.2.13/templates/managed-alb-https-v2.yaml#L5-L8
# Also, update DNS for minidream.synapse.org to point to this ALB once deployed.
