# Provision a public load balancer in front of private miniDREAM EC2
# Based on prod/minidream-R-env-pub-prod-instance-ec2-alb-v2.yaml
template_path: "remote/managed-alb-https-v2.yaml"
stack_name: "minidream-rstudio-2021-ec2-alb"

parameters:
  Department: "CompOnc"
  Project: "CSBC"
  OwnerEmail: "bruno.grande@sagebase.org"
  Ec2InstanceId: !stack_output "prod/minidream-rstudio-2021-ec2.yaml::Ec2InstanceId"
  SSLCertificateIdArn: "arn:aws:acm:us-east-1:055273631518:certificate/992c2d49-579a-465e-beff-1a08c284f7db"
  VpcId: "vpc-e66bd19d"   # computevpc
  AppPort: "443"          # nginx reverse proxy
  Subnets: "subnet-21a68d7c,subnet-4f3e2b2b,subnet-77d1e458"  # public subnets

# After deployment, Ec2SecurityGroup must be manually attached to the EC2 referenced by Ec2InstanceId:
# https://github.com/Sage-Bionetworks/aws-infra/blob/v0.2.13/templates/managed-alb-https-v2.yaml#L5-L8
# Also, update DNS for minidream.synapse.org to point to this ALB once deployed.

hooks:
  before_launch:
    - !cmd "wget https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.2.13/managed-alb-https-v2.yaml -N -P templates/remote"
