# Provision an EC2 instance for hosting miniDREAM RStudio server
# Based on the PR here: https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/504/files

template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.4.0/EC2/jc-ec2-linux.j2"
stack_name: "minidream-rstudio-2022-ec2"

sceptre_user_data:
  Distro: "ubuntu"
  OpenPorts: ["443"]  # On a private subnet (default)
parameters:
  VpcName: "computevpc"
  AMIId: "ami-0a3c3e0cb6ae0cc6c"  # packer-base-ubuntu-bionic-v1.0.9
  InstanceType: "x2gd.8xlarge"     # 32 vCPUs / 512 GiB
  VolumeSize: "500"
  BackupEc2: "true"
  SnapshotCount: "3"
  JcUserId: "lingling.peng@sagebase.org"

  JcConnectKey: !ssm "/infra/JcConnectKey"
  JcServiceApiKey: !ssm "/infra/JcServiceApiKey"
  JcSystemsGroupId: !ssm "/infra/JcSystemsGroupId"
stack_tags:
  Department: "SCCE"
  Project: "CSBC"
  OwnerEmail: "lingling.peng@sagebase.org"
  CostCenter: "CSBC - NCI / 101300"
