# Provision an EC2 instance
template_path: managed-ec2.yaml
stack_name: mpower2-user-add
parameters:
  # The Sage deparment for this resource
  Department: "Systems Biology"
  # The Sage project this resource will be used for
  Project: "AT-HOME PD"
  # The resource owner
  OwnerEmail: "phil.snyder@sagebase.org"
  # EC2 instance type (available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t2.micro"
  AMIId: "ami-0c7cdeb6546281c1a"

  # Integrate with our cloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_update:
    - !ec2_notify {{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}
