# Provision an EC2 instance
template_path: managed-ec2-v5.yaml
stack_name: nf-salmon
parameters:
  # The Sage deparment for this resource
  Department: "CompOnc"
  # The Sage project this resource will be used for
  Project: "NF"
  # The resource owner
  OwnerEmail: "sara.gosline@sagebase.org"
  AMIId: "ami-084302eb33c52749d"
  # EC2 instance type (available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "m5.4xlarge"
  VolumeSize: "100"
  
  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !ec2_notify {{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}
