# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template:
  type: "http"
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.9.0/templates/S3/synapse-external-bucket.j2"
stack_name: "nf-syn53689508-s3"
stack_tags:
  OwnerEmail: 'jineta.banerjee@sagebionetworks.org'
  CostCenter: "JHU NTAP / 301100"
parameters:
  # The following parameters are only examples they are not required.
  # You may omit them if you do not need to override the defaults.
  # (Optional) true (default) to encrypt bucket, false for no encryption
  # (Optional) true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: 'true'
  # (Optional) Synapse username (default: ""), required if AllowWriteBucket=true
  # (Optional) Allow accounts, groups, and users to access bucket (default is no access).
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'   # Required ARN for a synapse bucket
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/jineta.banerjee@sagebase.org'
    - 'arn:aws:iam::728882028485:role/ntap-add5-project-TowerForgeBatchHeadJobRole-X9Y068JVFXHC' ## Sage NF Tower access
    - 'arn:aws:iam::728882028485:role/ntap-add5-project-TowerForgeBatchWorkJobRole-TYLG8H2QIS7R' ## Sage NF Tower access
    - 'arn:aws:iam::728882028485:role/ntap-add5-project-TowerForgeServiceRole-1KZP8QDA7AR8P'  ## Sage NF Tower access
    - 'arn:aws:sts::728882028485:assumed-role/AWSReservedSSO_TowerViewer_fd6aee98ec127705/jineta.banerjee@sagebase.org' ## Sage NF Tower access
    - 'arn:aws:iam::184059545989:role/NCBI-CSVM-Service'  ## NCBI SRA DATA DELIVERY
    - 'arn:aws:iam::783971887864:role/NCBI-CSVM-Service'  ## NCBI SRA DATA DELIVERY
  # Enable Intelligent-tiering storage
  EnableDataLifeCycle: 'Enabled'
  LifecycleDataStorageClass: 'INTELLIGENT_TIERING'
sceptre_user_data:
  SynapseIDs:
    - "3342573"
    - "3389310"
    - "3421893"
