# Provision an EC2 instance
template_path: templates/managed-ec2-v2.yaml
stack_name: tesla-analysis-ec2
parameters:
  # The Sage deparment for this resource
  Department: "CompOnc"
  # The Sage project this resource will be used for
  Project: "TESLA"
  # The resource owner
  OwnerEmail: "xengie.doan@sagebase.org"
  # EC2 instance type (available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t3.2xlarge"
  # (Optional) ID of the AMI to deploy
  AMIId: "ami-0c031218cbaf1204f"  # AWS linux with 100GB encrypted boot volume

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !notify_ec2

