# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template_path: SynapseExternalBucket.yaml
stack_name: test1-kdaily-encryptedexternals3
parameters:
  # true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: "true"
  # Synapse username
  SynapseUserName: "gates-ki-service"
  # true to encrypt bucket, false (default) for no encryption
  EncryptBucket: "true"
  # Bucket owner's email address
  OwnerEmail: kenneth.daily@sagebase.org
hooks:
  after_create:
    - !synapse_bucket_notify {{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}
