# Provision an EC2 instance
template_path: templates/managed-ec2-v3.yaml
stack_name: test-size-change
parameters:
  # The Sage deparment for this resource
  Department: "Platform"
  # The Sage project this resource will be used for
  Project: "Infrastructure"
  # The resource owner
  OwnerEmail: "thomas.yu@sagebase.org"
  # (Optional) EC2 instance type, default is "t2.nano" (other available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t2.medium"
  # (Optional) Boot volume size, default is 8gb, Max is 500gb
  VolumeSize: 55
   # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !notify_ec2