# Provision an EC2 instance
template_path: remote/managed-rds-postgres-v1.j2
stack_name: test-ahayden-rds-postgres
sceptre_user_data:
  # (Required) Expose database ports to this whitelist of CIDR blocks
   OpenIngress: ["207.109.76.122"]
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "Platform"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "iAtlas-testing"
  # The resource owner
  OwnerEmail: "aaron.hayden@sagebase.org"

  # Set unique database user and password values in ssm with a path specific to the project
  DBMasterUsername: !ssm /iAtlas/postgresql/dev/test-ahayden-rds-postgres-username
  DBMasterUserPassword: !ssm /iAtlas/postgresql/dev/test-ahayden-rds-postgres-password
  #
  # Set SSL/TLS CSR values
  DomainName: "iatlasdb.sagebionetworks.org"
  ValidationDomain: "sagebionetworks.org"

  # Default account settings, leave alone unless you plan to override
  VpcName: "computevpc"

  # Settings have default values but can be overriden. Set the below
  # parameters *only* if you want to override the defaults.

  # (Optional) DB instance type, default is "db.t3.small" (other available types https://aws.amazon.com/rds/postgresql/pricing/)
  InstanceType: "db.t3.small"
  # (Optional) EC2 boot volume size in GB, default is 8GB, Max is 1000GB
  VolumeSize: "200"
  # (Optional) Run DB instance in a subnet (default: PrivateSubnet) (valid values: PrivateSubnet or PublicSubnet)
  # This parameter is independent of ingress whitelist
  VpcSubnet: "PublicSubnet"

# For CI system (do not change)
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-rds-postgres-v1.j2 --create-dirs -o templates/remote/managed-rds-postgres-v1.j2"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-rds-postgres-v1.j2 --create-dirs -o templates/remote/managed-rds-postgres-v1.j2"
  after_create:
    - !ec2_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"
