# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template:
  type: "http"
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.5.0/templates/S3/synapse-external-bucket.j2"
stack_name: "VEOIBD-S3-USA"
stack_tags:
  OwnerEmail: "dan.lu@sagebase.org"
  CostCenter: "Helmsley VEOIBD / 314100"
parameters:
  # The following parameters are only examples they are not required.
  # You may omit them if you do not need to override the defaults.
  # (Optional) true (default) to encrypt bucket, false for no encryption
  # (Optional) true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: 'true'
  # (Optional) Synapse username (default: ""), required if AllowWriteBucket=true
  # (Optional) Allow accounts, groups, and users to access bucket (default is no access).
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'   # Required ARN for a synapse bucket
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/dan.lu@sagebase.org'
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/jessica.vera@sagebase.org'
  EnableDataLifeCycle: "Enabled"
  LifecycleDataStorageClass: "INTELLIGENT_TIERING"
sceptre_user_data:
  SynapseIDs:
    - "3434599"
