# Provision an EBS volume for wpoehlm-ios-ec2 instance
template_path: remote/managed-ebs.yaml
stack_name: wpoehlm-iops-ec2-ebs-vol
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "NDR"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "amp-ad"
  # The resource owner
  OwnerEmail: "william.poehlman@sagebase.org"

  AvailabilityZone: "us-east-1a"
  VolumeType: "io1"
  Size: "1280"
  Iops: "64000"
  Ec2InstanceId: "i-0960d784a9185f87e"
  AttachmentDevice: "/dev/xvdb"

# For CI system (do not change)
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ebs.yaml --create-dirs -o templates/remote/managed-ebs.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ebs.yaml --create-dirs -o templates/remote/managed-ebs.yaml"
