sudo: false
language: python
python: 3.6
cache: pip
fast_finish: true
branches:
  only:
  - master
install:
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - pip install yamllint cfn-lint
  - pip install git+git://github.com/cloudreach/sceptre@v2.1.2
  - pip install git+git://github.com/zaro0508/sceptre-ssm-resolver.git
  - pip install git+git://github.com/zaro0508/sceptre-date-resolver.git
  - pip install git+git://github.com/Sage-Bionetworks/sceptre-provisioner-hooks.git
stages:
  - name: validate
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: validate
      script:
        - yamllint ./config ./templates
        - ./lint_stack.sh -l ./config/prod
        - cfn-lint ./templates/**/*
    - stage: deploy
      script:
        - ./lint_stack.sh -r
        - travis_wait 30 sceptre launch prod --yes

