language: python
python: 3.8
cache: pip
env:
  global:
    - REPO_NAME="${PWD##*/}"
    - AWS_PROFILE="ci-role"
    - AWS_REGION="us-east-1"
install:
  # install awscli v2
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip && sudo ./aws/install
  # install other tools
  - pip install pre-commit travis-wait-improved sceptre sceptre-ssm-resolver
before_script:
  - mkdir -p ~/.aws
  - echo -e "[profile ${AWS_PROFILE}]\nregion=${AWS_REGION}\nsource_profile=ci-user\nrole_arn=${AwsCfServiceRoleArn}" > ~/.aws/config
  - echo -e "[ci-user]\nregion=${AWS_REGION}\naws_access_key_id=${AwsTravisAccessKey}\naws_secret_access_key=${AwsTravisSecretAccessKey}" > ~/.aws/credentials
stages:
  - name: validate
  - name: deploy
    if: type = push AND branch = master
jobs:
  include:
    - stage: validate
      script:
        - pre-commit run --all-files
    - stage: deploy
      script:
        - '[ "$(ls -A ./config/prod)" ] && AWS_PROFILE=${AWS_PROFILE} travis_wait 30 sceptre launch prod --prune --yes || echo "No Stacks"'
