Description: Setup service account and roles for Emory pipeline lambda
AWSTemplateFormatVersion: 2010-09-09

Resources:
  # !! IMPORTANT !! - AWS API will refuse to remove users that have attached resources.
  # Therefore you must do the following before deleting them from this file:
  # 1. Detach or remove the following user resources: login profile, attached
  #    MFA device, access-keys, ssh-keys, and policies.
  # 2. Detach the user from all groups.
  LambdaArtifactsBucket:
    Type: 'AWS::S3::Bucket'

  # Allow public read on lambda bucket so that build users can read from it
  # Same as bootstrap bucket https://github.com/Sage-Bionetworks/aws-infra/blob/206c4b0ecafc8966561a2bfb3adfeb9ffa872048/templates/bootstrap.yaml#L66
  LambdaArtifactsBucketBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref LambdaArtifactsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowPublicRead"
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${LambdaArtifactsBucket}/*"

Outputs:
  LambdaArtifactsBucketName:
    Value: !Ref LambdaArtifactsBucket
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-LambdaArtifactsBucketName'
  LambdaArtifactsBucketArn:
    Value: !GetAtt LambdaArtifactsBucket.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-LambdaArtifactsBucketArn'
